version: '3.9'

# NOTE: local development only
services:
  onetl:
    image: docker.rep.msk.mts.ru/bigdata/platform/onetools/onetl:develop
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: base
    env_file: .env.docker
    volumes:
    - ./:/app/
    networks:
    - onetl
    - default
    extra_hosts:
    - rep.msk.mts.ru:10.73.8.86
    ulimits:
      # https://stackoverflow.com/a/56895801
      nofile:
        soft: 10000
        hard: 10000
    # no dependencies from other containers to allow running limited set of tests instead of all


  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
    - 27017:27017
    env_file: .env.dependencies
    networks:
    - onetl

  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    env_file: .env.dependencies
    ports:
    - 9010:9000
    - 9011:9001
    networks:
    - onetl

  postgres:
    image: docker.rep.msk.mts.ru/bigdata/platform/onetools/postgres:develop
    build:
      dockerfile: ./docker/postgres/Dockerfile
      context: .
    restart: unless-stopped
    env_file: .env.dependencies
    ports:
    - 5432:5432
    networks:
    - onetl

  greenplum:
    image: datagrip/greenplum:6.8
    restart: unless-stopped
    env_file: .env.dependencies
    ports:
    - 5433:5432
    networks:
    - onetl

  hive2:
    image: docker.rep.msk.mts.ru/bigdata/platform/onetools/onetl/hive2:develop
    build:
      dockerfile: ./docker/hive2/Dockerfile
      context: .
    hostname: hive2
    restart: unless-stopped
    env_file: .env.dependencies
    depends_on:
    - postgres
    ports:
    - 50010:50010
    - 50020:50020
    - 50070:50070
    - 50075:50075
    - 10000:10000
    - 10020:10020
    - 19888:19888
    - 9000:9000
    - 8030:8030
    - 8031:8031
    - 8032:8032
    - 8033:8033
    - 8040:8040
    - 8042:8042
    - 8088:8088
    networks:
    - onetl

  oracle:
    image: docker.rep.msk.mts.ru/bigdata/platform/onetools/onetl/oracle:develop
    build:
      dockerfile: ./docker/oracle/Dockerfile
      context: .
    restart: unless-stopped
    env_file: .env.dependencies
    ports:
    - 1522:1521
    - 5501:5500
    networks:
    - onetl

  webdav:
    image: docker.rep.msk.mts.ru/bigdata/platform/onetools/onetl/webdav:develop
    build:
      dockerfile: ./docker/webdav/Dockerfile
      context: .
    hostname: webdav
    restart: unless-stopped
    env_file: .env.dependencies
    ports:
    - 8000:80
    - 8443:443
    networks:
    - onetl

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports:
    - 8123:8123
    - 9001:9000
    networks:
    - onetl

  mysql:
    image: mysql
    restart: unless-stopped
    env_file: .env.dependencies
    ports:
    - 3306:3306
    networks:
    - onetl

  mssql:
    image: mcmoe/mssqldocker
    restart: unless-stopped
    env_file: .env.dependencies
    ports:
    - 1433:1433
    networks:
    - onetl

networks:
  onetl:
    name: onetl
